# Generated by Django 3.2 on 2021-10-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(db_index=True, verbose_name='valuation date')),
                ('rate_value', models.DecimalField(db_index=True, decimal_places=6, max_digits=18, verbose_name='rate value')),
                ('exchanged_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dani_exchange.currency', verbose_name='exchanged currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='dani_exchange.currency', verbose_name='source currency')),
            ],
            options={
                'verbose_name': 'currency exchange rate',
                'verbose_name_plural': 'currency exchange rates',
                'ordering': ['valuation_date'],
            },
        ),
    ]
